### PR TITLE
Fix UDP test.

### PR DESCRIPTION
**Pull request by malmrose**

### CODE REVIEW

**Comment by nothings** [comment]
Does this actually "fix" it in the sense that the old code fails and the new code works on your machine? Because I don't see how byte swapping the port can fix that (see comment by the port numbers), and that seems to be the only real change.

Also, it needs to use SDL, not arpa/inet. There are SDL functions for converting to network byte order (I don't remember what they are now, though).

**Comment by malmrose** [comment]
Yes, this patch works on my (Linux) machine. 

Patch updated to use SDL byte-swapping.

**Comment by nothings** [comment]
But did the previous version fail on your machine?

**Comment by malmrose** [comment]
Yes, without the byte-swap it doesn't receive anything because the port is incorrect.

**Comment by nothings** [comment]
But how is it incorrect? It's byte-reversed the same in both places... oh my god, you only need to byte reverse in the send, not in the open?!? _shakes fist_

**Comment by nothings** [comment]
I manually made the change and verified it, thank  you! Not merging officially because I want to make the change on-stream.

**Comment by malmrose** [comment]
I'll be sure to watch.

**Pull request closed without merging**
